# vim: filetype=sh
abbr h "cd ~/; and ls -a"
abbr d "cd ~/Documents; and ls -a"
abbr D "cd ~/Downloads; and ls -a"
abbr m "cd ~/Music; and ls -a"
abbr pp "cd ~/Pictures; and ls -a"
abbr vv "cd ~/Videos; and ls -a"
abbr cf "cd ~/.config; and ls -a"
abbr sc "cd ~/.scripts; and ls -a"
abbr mn "cd /mnt; and ls -a"
abbr bf "$EDITOR ~/.bmfiles"
abbr bd "$EDITOR ~/.bmdirs"
abbr cfb "$EDITOR ~/.bashrc"
abbr cfa "$EDITOR ~/.aliasrc"
abbr cfz "$EDITOR ~/.zshrc"
abbr cfv "$EDITOR ~/.config/nvim/init.vim"
abbr cfr "$EDITOR ~/.config/ranger/rc.conf"
abbr cfi "$EDITOR ~/.config/i3/config"
abbr cfm "$EDITOR ~/.config/mutt/muttrc"
abbr eb "$EDITOR ~/Documents/LaTeX/uni.bib"
abbr cv "$EDITOR ~/Documents/LaTeX/cv.tex"
abbr cfd "$EDITOR ~/.Xdefaults"
abbr cfu "$EDITOR ~/.config/newsboat/urls"
abbr cfn "$EDITOR ~/.config/newsboat/config"
abbr cfmb "$EDITOR ~/.config/ncmpcpp/bindings"
abbr cfmc "$EDITOR ~/.config/ncmpcpp/config"
abbr er "$EDITOR ~/.referbib"
